### ISSUE TITLE
Can't recognise 'python fb.py' as an internal or external command

### ISSUE THREAD

**Issue by Mccallum1983** [mdiazcl/fuzzbunch-debian#6]
I followed your instructions exactly however I get this error when I run 👍 
C:\fuzzbunch-debian\windows>python fb.py

**Comment by TheLawsOfChaos** [comment]
Sounds like you didn't put the fb.py file where it needs to go. Not sure how you did the installation, but here's how I do mine:
`#fuzzbunch stuff
apt install wine winbind winetricks -y
dpkg --add-architecture i386 && apt-get update && apt-get install wine32 -y

# Start a wine32 environment
WINEPREFIX="$HOME/.wine-fuzzbunch" WINEARCH=win32 wine wineboot

# Change WINEPREFIX for this session (modify your .bashrc accordingly if you want to make it permanent)
export WINEPREFIX=$HOME/.wine-fuzzbunch

cd $HOME/.wine-fuzzbunch/drive_c
git clone https://github.com/mdiazcl/fuzzbunch-debian.git

cd ~/.wine-fuzzbunch/drive_c/fuzzbunch-debian/installers
wine start python-*
wine start pywin32-*`

Don't forget to add the registry key : 
`HKCU\Environment  PATH "c:\\windows;c:\\windows\\system;C:\\Python26;C:\\fuzzbunch-debian\\windows\\fuzzbunch"`

Otherwise inside wine it won't know where to look for python files.

**Comment by Mccallum1983** [comment]
I did in fact have fb.py in the wrong folder, thank you.
